### PR TITLE
Fix bower paths in grunt server task

### PR DESCRIPTION
**Pull request by nsonnad**
The bower components were not being copied to the `.tmp` directory. This was causing the page created by `grunt server` to 404 on all bower components.

### CODE REVIEW

**Comment by heavysixer** [comment]
I just pulled your branch and am getting 404s on all the dependencies is it working for you locally?

```
Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:2 Uncaught ReferenceError: $ is not defined
basic.html:57 Uncaught ReferenceError: $ is not defined
bootstrap.js:7 Uncaught Error: Bootstrap's JavaScript requires jQuery
```

**Comment by heavysixer** [comment]
figured it out, will merge this and fix the local server.

**Comment by nsonnad** [comment]
Thanks, sorry I was having an over-caffeinated git rebase nightmare. I left one `copy:bower` off and was trying to clean up the commits. It didn't go well.

**Comment by heavysixer** [comment]
No worries! I appreciate you helping me out on this. I'm the only one who has installed this app, and obviously i just copied the bower_components over from another proj instead of installing it correctly.

**Comment by heavysixer** [comment]
You should be able to pull master now.

**Pull request merged**
